basePath: /v1
consumes:
- application/json
definitions:
  Song:
    description: Song defines a song
    properties:
      artist:
        description: Artist name
        type: string
        x-go-name: Artist
      name:
        description: Song name
        type: string
        x-go-name: Name
    required:
    - name
    - artist
    type: object
    x-go-package: github.com/biancarosa/music-data/models
host: localhost
info:
  description: the purpose of this application is to provide information about music.
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: there are no TOS at this moment, use at your own risk we take no
    responsibility
  title: Music Data API.
  version: 0.1.0
paths:
  /healthcheck:
    get:
      description: We will check some info regarding the application health, including
        memory stats.
      operationId: HealthCheck
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/healthCheckResponse'
      schemes:
      - https
      summary: Returns information about our application health.
  /song:
    get:
      description: We will retrieve some info in other APIs and in our database.
      operationId: Song
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/songResponse'
      schemes:
      - https
      summary: Returns information about a song.
produces:
- application/json
responses:
  healthCheckResponse:
    description: songResponse defines the response that you get of a valid healthcheck.
    schema:
      properties:
        application:
          properties:
            goroutines:
              description: Number of open goroutines.
              format: int64
              type: integer
              x-go-name: Goroutines
            heapAlloc:
              description: Allocated memory for the application.
              type: string
              x-go-name: HeapAlloc
          required:
          - goroutines
          - heapAlloc
          type: object
          x-go-name: Application
        applicationVersion:
          description: Application version
          type: string
          x-go-name: ApplicationVersion
      required:
      - applicationVersion
      type: object
  songResponse:
    description: songResponse defines the response that you get of a valid song.
    schema:
      $ref: '#/definitions/Song'
schemes:
- http
- https
swagger: "2.0"
